use std::fs;
use std::io;
use std::path::{Path, PathBuf};

fn main() -> io::Result<()> {
    let commands_dir = Path::new("src/commands");

    println!("cargo:rerun-if-changed={}", commands_dir.display());

    generate_mods(commands_dir)?;

    Ok(())
}

fn generate_mods(dir: &Path) -> io::Result<()> {
    let mut modules = Vec::new();

    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();

        if path.is_dir() {
            generate_mods(&path)?;

            let name = path.file_name().unwrap().to_string_lossy();
            modules.push(format!("pub mod {};", name));
        } else if path.extension().is_some_and(|e| e == "rs") {
            let stem = path.file_stem().unwrap().to_string_lossy();

            if stem != "mod" {
                modules.push(format!("pub mod {};", stem));
            }
        }
    }

    modules.sort();

    let mod_rs: PathBuf = dir.join("mod.rs");

    let content = format!(
        "// AUTO-GENERATED BY build.rs\n{}\n",
        modules.join("\n")
    );

    fs::write(mod_rs, content)?;

    Ok(())
}
