// AUTO-GENERATED BY build.rs
pub mod about;
pub mod botinfo;
pub mod botinvite;
pub mod bugreport;
pub mod donate;
pub mod invite;
pub mod release;
pub mod servericon;
pub mod serverinfo;
pub mod support;
pub mod userinfo;
pub mod vote;
