// AUTO-GENERATED BY build.rs
pub mod calc;
pub mod esay;
pub mod help;
pub mod hexcolor;
pub mod morse;
pub mod nodmhelp;
pub mod ping;
pub mod say;
pub mod sdm;
pub mod shortlink;
pub mod translate;
pub mod weather;
pub mod wiki;
